In [24]:
import tensorflow as tf
import numpy as np
from IPython.display import display

xy = np.loadtxt('data/lab06_train.txt', unpack=True, dtype='float32')
x_data = np.transpose(xy[0:3])
y_data = np.transpose(xy[3:])

X = tf.placeholder('float', [None, 3])
Y = tf.placeholder('float', [None, 3])

W = tf.Variable(tf.zeros([3,3]))

hypothesis = tf.nn.softmax(tf.matmul(X, W))
learning_rate = 0.001
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), reduction_indices=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate).minimize(cost)

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)

    for step in range(2001):
        sess.run(optimizer, feed_dict={X:x_data, Y:y_data})
        if step % 20 == 0:
            print(step, "cost:%s, W:%s"%(sess.run(cost, feed_dict={X:x_data, Y:y_data}), sess.run(W)))
    
    a = sess.run(hypothesis, feed_dict={X:[[1,11,7]]})
    print("a : %s, arg_max(a) : %s" % (a, sess.run(tf.arg_max(a, 1))))
    b = sess.run(hypothesis, feed_dict={X:[[1,3,4]]})
    print("b : %s, arg_max(c) : %s" % (b, sess.run(tf.arg_max(b, 1))))
    c = sess.run(hypothesis, feed_dict={X:[[1,1,0]]})
    print("c : %s, arg_max(b) : %s" % (c, sess.run(tf.arg_max(c, 1))))
    all_data = sess.run(hypothesis, feed_dict={X:[[1,11,7], [1,3,4], [1,1,0]]})
    print("all_data : %s, arg_max(all_data) : %s" % (all_data, sess.run(tf.arg_max(all_data, 1))))


0 cost:1.09774, W:[[ -8.33333252e-05   4.16666626e-05   4.16666480e-05]
 [  1.66666694e-04   2.91666773e-04  -4.58333408e-04]
 [  1.66666636e-04   4.16666706e-04  -5.83333429e-04]]
20 cost:1.08463, W:[[-0.00183376  0.00067546  0.0011583 ]
 [ 0.00306666  0.00510665 -0.00817331]
 [ 0.00307154  0.00773401 -0.01080555]]
40 cost:1.07688, W:[[-0.00370558  0.00100114  0.00270444]
 [ 0.00534192  0.00835268 -0.0136946 ]
 [ 0.00535842  0.01348236 -0.01884078]]
60 cost:1.07203, W:[[-0.00566168  0.00110187  0.00455982]
 [ 0.00718558  0.01045809 -0.01764366]
 [ 0.00721834  0.01808493 -0.02530327]]
80 cost:1.06878, W:[[-0.00767988  0.00103789  0.00664199]
 [ 0.00871126  0.01173282 -0.02044407]
 [ 0.00876411  0.0218481  -0.03061221]]
100 cost:1.06645, W:[[-0.00974582  0.00085278  0.00889304]
 [ 0.00999095  0.01240054 -0.02239149]
 [ 0.01006747  0.02499313 -0.0350606 ]]
120 cost:1.06465, W:[[-0.01184951  0.00057812  0.01127139]
 [ 0.0110741   0.01262292 -0.02369701]
 [ 0.0111778   0.02768007 -0.038857