# XOR problem

In [3]:
import tensorflow as tf
import numpy as np

In [43]:
xy = np.loadtxt('data/lab09_train.txt', unpack=True)
x_data = xy[0:-1]
y_data = xy[-1]

X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

W = tf.Variable(tf.random_uniform([1, len(x_data)], -1.0, 1.0))

h = tf.matmul(W, X)
hypothesis = tf.div(1., 1. + tf.exp(-h))
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))

a = tf.Variable(0.01)
optimizer = tf.train.GradientDescentOptimizer(a)
train = optimizer.minimize(cost)

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    
    for step in range(1001):
        sess.run(train, feed_dict={X:x_data, Y:y_data})
        if step % 200 == 0:
            print(step, "cost:%s, W:%s"%(sess.run(cost, feed_dict={X:x_data, Y:y_data}), sess.run(W)))
    
    correct_prediction = tf.equal(tf.floor(hypothesis + 0.5), Y)
    accuracy = tf.reduce_mean(tf.cast(correct_prediction, "float"))
    hypothesis_result, hypothesis_plus_0_5_result, correct_prediction_result, accuracy_result = sess.run([hypothesis,
              tf.floor(hypothesis + 0.5), 
              correct_prediction, accuracy], 
             feed_dict={X:x_data, Y:y_data})
    print('hypothesis_result : %s\n, hypothesis_plus_0_5_result : %s\n, correct_prediction_result : %s\n, accuracy_result : %s' % (hypothesis_result, hypothesis_plus_0_5_result, correct_prediction_result, accuracy_result))
    print("Accuracy : %s" % accuracy.eval({X:x_data, Y:y_data}))


0 cost:0.75771, W:[[ 0.84130788  0.31895521]]
200 cost:0.726918, W:[[ 0.63996345  0.17541413]]
400 cost:0.71066, W:[[ 0.48931593  0.07769651]]
600 cost:0.702366, W:[[ 0.37803715  0.01402295]]
800 cost:0.698171, W:[[ 0.29594305 -0.02565307]]
1000 cost:0.696024, W:[[ 0.23501799 -0.0489596 ]]
hypothesis_result : [[ 0.5         0.48776251  0.55848551  0.54638088]]
, hypothesis_plus_0_5_result : [[ 1.  0.  1.  1.]]
, correct_prediction_result : [[False False  True False]]
, accuracy_result : 0.25
Accuracy : 0.25


# NN for XOR

In [65]:
xy = np.loadtxt('data/lab09_train.txt', unpack=True)
x_data = np.transpose(xy[0:-1])
y_data = np.reshape(xy[-1], (4,1))

X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

W1 = tf.Variable(tf.random_uniform([2, 2], -1.0, 1.0))
W2 = tf.Variable(tf.random_uniform([2, 1], -1.0, 1.0))

b1 = tf.Variable(tf.zeros([2]), name="Bias1")
b2 = tf.Variable(tf.zeros([1]), name="Bias2")

L2 = tf.sigmoid(tf.matmul(X, W1) + b1)
hypothesis = tf.sigmoid(tf.matmul(L2, W2) + b2)
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))

a = tf.Variable(0.1)
optimizer = tf.train.GradientDescentOptimizer(a)
train = optimizer.minimize(cost)

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    
    for step in range(30001):
        sess.run(train, feed_dict={X:x_data, Y:y_data})
        if step % 2000 == 0:
            print(step, "cost:%s, W1:%s, W2:%s"%(sess.run(cost, feed_dict={X:x_data, Y:y_data}), sess.run(W1), sess.run(W2)))
    
    correct_prediction = tf.equal(tf.floor(hypothesis + 0.5), Y)
    accuracy = tf.reduce_mean(tf.cast(correct_prediction, "float"))
    hypothesis_result, correct_prediction_result, accuracy_result = sess.run([tf.floor(hypothesis + 0.5),
              correct_prediction, accuracy], 
             feed_dict={X:x_data, Y:y_data})
    print('hypothesis+0.5_result : %s\n,correct_prediction_result : %s\n, accuracy_result : %s' % (hypothesis_result, correct_prediction_result, accuracy_result))
    print("Accuracy : %s" % accuracy.eval({X:x_data, Y:y_data}))


0 cost:0.717726, W1:[[-0.10278358 -0.85798699]
 [ 0.86678773 -0.97411072]], W2:[[-0.7152313 ]
 [-0.14862718]]
2000 cost:0.556729, W1:[[-0.11979686 -3.17249751]
 [ 1.32023442 -3.28428459]], W2:[[-0.80255145]
 [-3.29000449]]
4000 cost:0.206334, W1:[[ 2.35175347 -5.20473385]
 [ 2.43795872 -5.49564838]], W2:[[-4.74103832]
 [-6.22867489]]
6000 cost:0.0479717, W1:[[ 3.87317181 -5.968822  ]
 [ 3.88988352 -6.1156373 ]], W2:[[-7.9943347 ]
 [-8.17705345]]
8000 cost:0.0250901, W1:[[ 4.38477135 -6.29945326]
 [ 4.39833403 -6.40576887]], W2:[[-9.26097584]
 [-9.21464348]]
10000 cost:0.0167586, W1:[[ 4.67378759 -6.5033989 ]
 [ 4.68551588 -6.59012651]], W2:[[-10.02699184]
 [ -9.89861393]]
12000 cost:0.0125171, W1:[[ 4.87095785 -6.64892912]
 [ 4.88143539 -6.72379589]], W2:[[-10.57425404]
 [-10.40637112]]
14000 cost:0.00996384, W1:[[ 5.01891565 -6.76124001]
 [ 5.02847481 -6.82801962]], W2:[[-10.99949551]
 [-10.80945778]]
16000 cost:0.00826368, W1:[[ 5.13651943 -6.85226917]
 [ 5.14536619 -6.91311598]], W2

# Wide NN for XOR

In [68]:
xy = np.loadtxt('data/lab09_train.txt', unpack=True)
x_data = np.transpose(xy[0:-1])
y_data = np.reshape(xy[-1], (4,1))

X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

W1 = tf.Variable(tf.random_uniform([2, 10], -1.0, 1.0))
W2 = tf.Variable(tf.random_uniform([10, 1], -1.0, 1.0))

b1 = tf.Variable(tf.zeros([10]), name="Bias1")
b2 = tf.Variable(tf.zeros([1]), name="Bias2")

L2 = tf.sigmoid(tf.matmul(X, W1) + b1)
hypothesis = tf.sigmoid(tf.matmul(L2, W2) + b2)
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))

a = tf.Variable(0.1)
optimizer = tf.train.GradientDescentOptimizer(a)
train = optimizer.minimize(cost)

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    
    for step in range(2001):
        sess.run(train, feed_dict={X:x_data, Y:y_data})
        if step % 200 == 0:
            print(step, "cost:%s, W1:%s, W2:%s"%(sess.run(cost, feed_dict={X:x_data, Y:y_data}), sess.run(W1), sess.run(W2)))
    
    correct_prediction = tf.equal(tf.floor(hypothesis + 0.5), Y)
    accuracy = tf.reduce_mean(tf.cast(correct_prediction, "float"))
    hypothesis_result, correct_prediction_result, accuracy_result = sess.run([tf.floor(hypothesis + 0.5),
              correct_prediction, accuracy], 
             feed_dict={X:x_data, Y:y_data})
    print('hypothesis+0.5_result : %s\n,correct_prediction_result : %s\n, accuracy_result : %s' % (hypothesis_result, correct_prediction_result, accuracy_result))
    print("Accuracy : %s" % accuracy.eval({X:x_data, Y:y_data}))


0 cost:0.92421, W1:[[ 0.08747642 -0.86024302  0.05532705  0.03872549 -0.59791541  0.05596437
  -0.65015954 -0.94750524  0.81878346 -0.13888203]
 [-0.58525002  0.10820794 -0.69871503 -0.82949907  0.48573837  0.10476074
  -0.65125    -0.40644607 -0.84757018 -0.11027693]], W2:[[-0.17806569]
 [-0.68579197]
 [ 0.94491625]
 [-0.9114753 ]
 [-0.20595205]
 [-0.01758343]
 [-0.37242204]
 [-0.70741796]
 [-0.89013183]
 [-0.41359749]]
200 cost:0.689314, W1:[[ 0.08289797 -0.85976291  0.09053345 -0.06370704 -0.6032719   0.05208735
  -0.69175071 -1.02221549  0.87517488 -0.14737082]
 [-0.59052747  0.04891171 -0.72021121 -0.84056389  0.48046511  0.10016528
  -0.69206142 -0.54210645 -0.78360182 -0.11826555]], W2:[[ 0.04585833]
 [-0.4638297 ]
 [ 1.17543876]
 [-0.69900662]
 [ 0.0188756 ]
 [ 0.20461653]
 [-0.2411965 ]
 [-0.58873969]
 [-0.66982424]
 [-0.19645578]]
400 cost:0.684844, W1:[[ 0.08268587 -0.8396318   0.09185185 -0.13208878 -0.60585445  0.04347407
  -0.72642052 -1.09570158  0.99400097 -0.14042133]


# Deep NN for XOR

In [75]:
xy = np.loadtxt('data/lab09_train.txt', unpack=True)
x_data = np.transpose(xy[0:-1])
y_data = np.reshape(xy[-1], (4,1))

X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

W1 = tf.Variable(tf.random_uniform([2, 5], -1.0, 1.0))
W2 = tf.Variable(tf.random_uniform([5, 4], -1.0, 1.0))
W3 = tf.Variable(tf.random_uniform([4, 1], -1.0, 1.0))

b1 = tf.Variable(tf.zeros([5]), name="Bias1")
b2 = tf.Variable(tf.zeros([4]), name="Bias2")
b3 = tf.Variable(tf.zeros([1]), name="Bias3")

L2 = tf.sigmoid(tf.matmul(X, W1) + b1)
L3 = tf.sigmoid(tf.matmul(L2, W2) + b2)
hypothesis = tf.sigmoid(tf.matmul(L3, W3) + b3)
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))

a = tf.Variable(0.3)
optimizer = tf.train.GradientDescentOptimizer(a)
train = optimizer.minimize(cost)

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    
    for step in range(4001):
        sess.run(train, feed_dict={X:x_data, Y:y_data})
        if step % 400 == 0:
            print(step, "cost:%s, W1:%s\n, W2:%s\n, W3:%s"%(sess.run(cost, feed_dict={X:x_data, Y:y_data}), 
                                                           sess.run(W1), 
                                                           sess.run(W2), 
                                                           sess.run(W3)))
    
    correct_prediction = tf.equal(tf.floor(hypothesis + 0.5), Y)
    accuracy = tf.reduce_mean(tf.cast(correct_prediction, "float"))
    hypothesis_result, correct_prediction_result, accuracy_result = sess.run([tf.floor(hypothesis + 0.5),
              correct_prediction, accuracy], 
             feed_dict={X:x_data, Y:y_data})
    print('hypothesis+0.5_result : %s\n,correct_prediction_result : %s\n, accuracy_result : %s' % (hypothesis_result, correct_prediction_result, accuracy_result))
    print("Accuracy : %s" % accuracy.eval({X:x_data, Y:y_data}))


0 cost:0.75454, W1:[[ 0.85422498 -0.91823816  0.30841005 -0.13595116  0.70689809]
 [-0.21000713 -0.81314665 -0.51228005 -0.32783511 -0.21083389]]
, W2:[[-0.62870491 -0.58640361  0.09692668  0.12470901]
 [-0.31490454 -0.75877005  0.49519071  0.54882789]
 [-0.47791952 -0.11283292 -0.64451545  0.54278803]
 [ 0.17856321 -0.50651544  0.94946808 -0.23821123]
 [-0.18133692  0.81648302  0.52799618 -0.67767531]]
, W3:[[ 0.81738001]
 [-0.36219925]
 [ 0.64675146]
 [ 0.44069317]]
400 cost:0.693043, W1:[[ 0.87969673 -0.81848419  0.33490193 -0.11786991  0.73612088]
 [-0.24970667 -0.73574483 -0.50707281 -0.321679   -0.23656562]]
, W2:[[-0.70142514 -0.57463747  0.07253422  0.10935738]
 [-0.45227733 -0.68713808  0.42191795  0.49390149]
 [-0.52453053 -0.11783025 -0.65351343  0.53365117]
 [ 0.14518337 -0.50566494  0.93674415 -0.25123239]
 [-0.24504419  0.82474834  0.50691122 -0.69159031]]
, W3:[[ 0.811023  ]
 [-0.36517477]
 [ 0.34289938]
 [ 0.18311407]]
800 cost:0.692467, W1:[[ 0.92898697 -0.78406113  0.

# Using Tensorboard

In [82]:
xy = np.loadtxt('data/lab09_train.txt', unpack=True)
x_data = np.transpose(xy[0:-1])
y_data = np.reshape(xy[-1], (4,1))

X = tf.placeholder(tf.float32, name = 'X-input')
Y = tf.placeholder(tf.float32, name = 'Y-input')

W1 = tf.Variable(tf.random_uniform([2, 5], -1.0, 1.0), name = 'Weight1')
W2 = tf.Variable(tf.random_uniform([5, 4], -1.0, 1.0), name = 'Weight2')
W3 = tf.Variable(tf.random_uniform([4, 1], -1.0, 1.0), name = 'Weight3')

b1 = tf.Variable(tf.zeros([5]), name = "Bias1")
b2 = tf.Variable(tf.zeros([4]), name = "Bias2")
b3 = tf.Variable(tf.zeros([1]), name = "Bias3")

with tf.name_scope('layer2') as scope:
    w1_hist = tf.summary.histogram('weights1', W1)
    b1_hist = tf.summary.histogram('biasses1', b1)
    L2 = tf.sigmoid(tf.matmul(X, W1) + b1)

with tf.name_scope('layer3') as scope:
    w2_hist = tf.summary.histogram('weights2', W2)
    b2_hist = tf.summary.histogram('biasses2', b2)
    L3 = tf.sigmoid(tf.matmul(L2, W2) + b2)
    
with tf.name_scope('layer4') as scope:
    w3_hist = tf.summary.histogram('weights3', W3)
    b3_hist = tf.summary.histogram('biasses3', b3)
    hypothesis = tf.sigmoid(tf.matmul(L3, W3) + b3)
    
with tf.name_scope('cost') as scope:
    cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))
    cost_sum = tf.summary.scalar('cost', cost)

with tf.name_scope('train') as scope:
    y_hist = tf.summary.histogram('y', Y)
    a = tf.Variable(0.3)
    optimizer = tf.train.GradientDescentOptimizer(a)
    train = optimizer.minimize(cost)

init = tf.global_variables_initializer()

with tf.Session() as sess:
    merged = tf.summary.merge_all()
    writer = tf.summary.FileWriter('./temp/xor_logs', sess.graph)
    sess.run(init)
    
    for step in range(4001):
        sess.run(train, feed_dict={X:x_data, Y:y_data})
        if step % 400 == 0:
            print(step, "cost:%s, W1:%s\n, W2:%s\n, W3:%s"%(sess.run(cost, feed_dict={X:x_data, Y:y_data}), 
                                                           sess.run(W1), 
                                                           sess.run(W2), 
                                                           sess.run(W3)))
    
    correct_prediction = tf.equal(tf.floor(hypothesis + 0.5), Y)
    accuracy = tf.reduce_mean(tf.cast(correct_prediction, "float"))
    hypothesis_result, correct_prediction_result, accuracy_result = sess.run([tf.floor(hypothesis + 0.5),
              correct_prediction, accuracy], 
             feed_dict={X:x_data, Y:y_data})
    print('hypothesis+0.5_result : %s\n,correct_prediction_result : %s\n, accuracy_result : %s' % (hypothesis_result, correct_prediction_result, accuracy_result))
    print("Accuracy : %s" % accuracy.eval({X:x_data, Y:y_data}))


KeyboardInterrupt: 